fix wroong data size when bpp=16 condition
chidea/FBpyGIF pull request #19
Opened 2018-06-23 15:45 UTC by eggfly

My Raspberry Pi's TFT screen's bpp(bits per pixel) is 16,
the line cut.tobytes('raw', 'BGRA' if bpp == 32 else 'BGR') in _ready_gif() returns a bytes data with 24 bits per pixel,
and then show_img() writes the img directly into framebuffer wrongly.
My solution is a workaround which not calling tobytes() function in _ready_gif() function, but passing the image obj directly into show_img()

2018-06-24 22:07 UTC, chidea commented
Thanks for your interest and time.
I'm concerned if this makes it not working on odroid C2.
Please wait until I get it tested.

2018-07-30 14:44 UTC, chidea requested changes
This is not ok..
The main purpose for report_fb() is to print the raw information bytes of frame buffer, to send it to me and let me test for that device.

2018-07-30 14:45 UTC, chidea approved these changes
Tested on variant devices I have and it seems to be working well with them too.

2018-07-30 14:45 UTC, merged

2018-07-30 15:56 UTC, chidea commented
Besides, your proposal makes every images to be unpacked to bytes on-the-fly which means huge loss of performance.
I'll just add case for 16 bpp in later version.

2018-08-04 16:40 UTC, eggfly commented
Thank you for your tests~ I'm not very good at English and  I'm a newbie for graphics programming. I read the code again and tried to understand the performance issue in the case of 16 bpp. I only have a hardware running on 16 bpp mode.